### ISSUE TITLE
Diehl 1992

### ISSUE THREAD

**Issue by jorgepiloto** [jorgepiloto/atmopy#1]
#### Explanation on the model :earth_africa: 
This is one of the first ever released atmospheric models. Since it is very simple, it should be easy to generate and include this model in the package :rocket: 

#### General data :information_source:  
**Name:** diehl22
**Author:** Walter S. Diehl
**Year:** 1922
**Paper:** "Notes on the Standard Atmosphere (NACA TN-99)" 

#### Tasks :memo: 

- [x] Create a `atmopy/diehl22 sub-package`
- [x] Include tests on previous model
- [x] Add official report/article
- [x] Properly documented functions

**Comment by jorgepiloto** [comment]
This model has been finally implemented!
