### ISSUE TITLE
Gregg 1921

### ISSUE THREAD

**Issue by jorgepiloto** [jorgepiloto/atmopy#2]
#### Explanation on the model :earth_africa: 
This is one of the first ever released atmospheric models and it differentiates between winter and summer conditions, thought results to not diverge so much from one season to another.

#### General data :information_source:  
**Name:** gregg21
**Author:** Willis Ray Gregg
**Year:** 1921
**Paper:** "Standard Atmosphere (NACA Report-147)" 

#### Tasks :memo: 

- [ ] Create a `atmopy/gregg21 sub-package`
- [ ] Include tests on previous model
- [ ] Add official report/article
- [ ] Properly documented functions
